[tools]
chezmoi = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
go = "latest"
helm = "latest"
neovim = "latest"
sd = "latest"
terraform = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
zellij = "latest"
